name: Feature request
description: Suggest an idea for Qi
labels: [enhancement]

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What's the use case or pain point?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What should the feature look like?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What have you tried or considered instead?
